### PR TITLE
Run on Node 16

### PR DESCRIPTION
**Pull request by markstos**
node12 is being deprecated.

### CODE REVIEW

**Comment by kevincobain2000** [comment]
Cool. Will do it soon.

**Comment by markstos** [comment]
Thanks for merging. Could you tag it and release it as well?

**Comment by kevincobain2000** [comment]
Oh will do tomorrow

**Comment by kevincobain2000** [comment]
Pushed https://github.com/kevincobain2000/action-cache-http/releases/tag/v3.1

**Pull request merged**
